#!/usr/bin/env perl
use strict;
use warnings;

use base 'Net::Server::HTTP';
use Getopt::Long;
use FindBin;
use File::Spec::Functions;

my $root;

sub process_http_request
{
    my ($self) = @_;
    local $ENV{ GIT_PROJECT_ROOT } = $root;
    local $ENV{ GIT_HTTP_EXPORT_ALL } = 1;
    $self->exec_cgi( catfile( $FindBin::Bin, 'git-http-backend' ) );
}

sub main
{
    my $port = 8123;
    GetOptions(
        'port=i' => \$port,
        'root=s' => \$root,
    );
    $root || die 'Missing mandatory --root option';
    __PACKAGE__->run( port => $port );
}

main( ) unless caller;
1;
